FROM tianon/true


ADD https://hydra.iohk.io/build/7366583/download/1/alonzo-purple-config.json          /config/alonzo-purple-config.json
ADD https://hydra.iohk.io/build/7366583/download/1/alonzo-purple-byron-genesis.json   /config/alonzo-purple-byron-genesis.json
ADD https://hydra.iohk.io/build/7366583/download/1/alonzo-purple-shelley-genesis.json /config/alonzo-purple-shelley-genesis.json
ADD https://hydra.iohk.io/build/7366583/download/1/alonzo-purple-alonzo-genesis.json  /config/alonzo-purple-alonzo-genesis.json
ADD https://hydra.iohk.io/build/7189190/download/1/alonzo-purple-topology.json        /config/alonzo-purple-topology.json
